# vault-values.yaml
server:
  affinity: ""
  ha:
    enabled: true
    replicas: 6
    raft: 
      enabled: true   
  readinessProbe:
    enabled: true
    path: "/v1/sys/health?standbyok=true&perfstandbyok=true&drsecondarycode=472"
  livenessProbe:
    enabled: true 
    path: "/v1/sys/health?standbyok=true&perfstandbyok=true&drsecondarycode=472"
  image:
    repository: hashicorp/vault-enterprise
    tag: 1.14.0-ent
  enterpriseLicense:
    secretName: vault-ent-license
injector:
  enabled: false
