# vault-values.yaml
server:
  affinity: ""
  ha:
    enabled: true
    replicas: 3
    raft: 
      enabled: true
      config: | 
        ui = true
        listener "tcp" {
          tls_disable = 1
          address = "[::]:8200"
          cluster_address = "[::]:8201"
        }

        storage "raft" {
            path = "/vault/data"
              retry_join {
                leader_api_addr = "http://vault-secondary-0.vault-secondary-internal:8200"
          }
            retry_join {
              leader_api_addr = "http://vault-secondary-1.vault-secondary-internal:8200"
            }
            retry_join {
              leader_api_addr = "http://vault-secondary-2.vault-secondary-internal:8200"
            }
        }   
  readinessProbe:
    enabled: true
    path: "/v1/sys/health?standbyok=true&sealedcode=204&uninitcode=204&perfstandbyok=true&drsecondarycode=200"
    initialDelaySeconds: 60

  livenessProbe:
    enabled: true
    path: "/v1/sys/health?standbyok=true&sealedcode=204&uninitcode=204&perfstandbyok=true&drsecondarycode=200"
    initialDelaySeconds: 60
  image:
    repository: hashicorp/vault-enterprise
    tag: 1.14.0-ent
  enterpriseLicense:
    secretName: vault-ent-license
injector:
  enabled: false
