defaultVaultConnection:
  enabled: true
  # Address of the Vault Server
  # Example: http://vault.default.svc.cluster.local:8200
  address: "http://vault.vault.svc.cluster.local:8200"
  skipTLSVerify: true

defaultAuthMethod:
  enabled: true
  mount: kubernetes
  kubernetes:
    role: test-role
    serviceAccount: default
    tokenAudiences:
      - http://kubernetes.default.svc.cluster.local 