global:
  enabled: true
  tlsDisable: true
server:
  affinity: ""
  ha:
    apiAddr: "http://vault-secondary-active.vault-secondary.svc.cluster.local:8200"
    clusterAddr: "http://$(HOSTNAME).vault-secondary-internal.vault-secondary.svc.cluster.local:8201"
    enabled: true
    replicas: 3
    raft:
      enabled: true
      config: | 
        ui = true
        service_registration "kubernetes" {}
        listener "tcp" {
          address = "[::]:8200"
          cluster_address = "[::]:8201"
          tls_disable = 1

        }

        storage "raft" {
            path = "/vault/data"
              retry_join {
                leader_api_addr = "http://vault-secondary-0.vault-secondary-internal:8200"
          }
            retry_join {
              leader_api_addr = "http://vault-secondary-1.vault-secondary-internal:8200"
            }
            retry_join {
              leader_api_addr = "http://vault-secondary-2.vault-secondary-internal:8200"
            }
        }
  image:
    repository: hashicorp/vault-enterprise
    tag: 1.14.0-ent
  enterpriseLicense:
    secretName: vault-ent-license
  readinessProbe:
    enabled: false
    path: '/v1/sys/health?standbyok=true&perfstandbyok=true'
  livenessProbe:
    enabled: false
    path: '/v1/sys/health?standbyok=true&perfstandbyok=true'

  



  