apiVersion: v1
kind: Pod
metadata:
  name: alpine
  namespace: vault
  labels:
    app: alpine
spec:
  containers:
  - image: alpine
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: alpine



