# Define a SecretProviderClass resource that describes parameters given to the CSI provider
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: test-secretproviderclass
  namespace: vault
spec:
  provider: vault
  parameters:
    vaultAddress: "https://vault.vault:8200"
    vaultSkipTLSVerify: "true"
    roleName: "test-role"
    objects: |
      - objectName: "test-object"
        secretPath: "test/data/secret"
        secretKey: "password"