apiVersion: rbac.authorization.k8s.io/v1  
kind: ClusterRoleBinding  
metadata:  
    name: k8s_token-review-clusterrolebindings  
roleRef:  
    apiGroup: rbac.authorization.k8s.io  
    kind: ClusterRole  
    name: system:auth-delegator  
subjects: 
    - kind: ServiceAccount  
      name: test-sa  
      namespace: vault
    - kind: ServiceAccount  
      name: default
      namespace: vso