apiVersion: apps/v1
kind: Deployment
metadata:
  name: openldap-auth-method
  labels:
    app.kubernetes.io/name: openldap-auth-method
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: openldap-auth-method
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: openldap-auth-method
    spec:
      containers:
        - name: openldap
          image: docker.io/bitnami/openldap:latest
          imagePullPolicy: "Always"
          env:
            - name: LDAP_ADMIN_USERNAME
              value: "admin"
            - name: LDAP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: adminpassword
                  name: openldap-auth-method
            - name: LDAP_USERS
              valueFrom:
                secretKeyRef:
                  key: users
                  name: openldap-auth-method
            - name: LDAP_PASSWORDS
              valueFrom:
                secretKeyRef:
                  key: passwords
                  name: openldap-auth-method
          ports:
            - name: tcp-ldap
              containerPort: 1389
---
apiVersion: v1
kind: Service
metadata:
  name: openldap-auth-method
  labels:
    app.kubernetes.io/name: openldap-auth-method
spec:
  type: ClusterIP
  ports:
    - name: tcp-ldap
      port: 1389
      targetPort: tcp-ldap
  selector:
    app.kubernetes.io/name: openldap-auth-method