---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: internal-app
  namespace: vault
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orgchart
  namespace: vault
  labels:
    app: orgchart
spec:
  selector:
    matchLabels:
      app: orgchart
  replicas: 1
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'test-role'
        vault.hashicorp.com/agent-configmap: 'my-configmap'
        vault.hashicorp.com/agent-pre-populate: 'true'
        vault.hashicorp.com/log-level: 'trace'
      labels:
        app: orgchart
    spec:
      serviceAccountName: internal-app
      containers:
        - name: orgchart
          image: jweissig/app:0.0.1
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
  namespace: vault
data:
  config.hcl: |
    "auto_auth" = {
      "method" = {
        "type" = "kubernetes"
        "config" = {
          "role" = "test-role"
        }
      }
      log_level= "trace"
      "sink" = {
        "config" = {
          "path" = "/home/vault/.token"
        }

        "type" = "file"
      }
    }

    "exit_after_auth" = false
    "pid_file" = "/home/vault/.pid"
    "log_level" = "trace"

    "template" = {
      "contents" = "{{ with secret \"database/creds/readonly\" }}{{ range $k, $v := .Data }}{{ $k }}: {{ $v }}\n{{ end }}{{ end }}"
      "destination" = "/vault/secrets/database-creds.txt"
    }

    "vault" = {
      "address" = "http://vault.vault.svc:8200"
    }

    cache {
      use_auto_auth_token = true
    }

    listener "tcp" {
      address = "0.0.0.0:8300"
      tls_disable = true  
    }

    template_config {
        exit_on_retry_failure = true
    }
    
  config-init.hcl: |
    "auto_auth" = {
      "method" = {
        "type" = "kubernetes"
        "config" = {
          "role" = "test-role"
        }
      }

      "sink" = {
        "config" = {
          "path" = "/home/vault/.token"
        }

        "type" = "file"
      }
    }

    cache {
      use_auto_auth_token = true
    }

    "exit_after_auth" = true
    "pid_file" = "/home/vault/.pid"
    "log_level" = "trace"

    "template" = {
      "contents" = "{{ with secret \"database/creds/readonly\" }}{{ range $k, $v := .Data }}{{ $k }}: {{ $v }}\n{{ end }}{{ end }}"
      "destination" = "/vault/secrets/database-creds.txt"
    }    

    "vault" = {
      "address" = "http://vault.vault.svc:8200"
    }

    listener "tcp" {
      address = "0.0.0.0:8300"
      tls_disable = true
    }

    template_config {
        exit_on_retry_failure = true
    }