apiVersion: v1
kind: ServiceAccount  
metadata:  
  name: test-sa  
  namespace: vault
---
apiVersion: v1  
kind: Secret  
metadata:  
  name: test-secret
  namespace: vault
  annotations:  
    kubernetes.io/service-account.name: test-sa  
type: kubernetes.io/service-account-token  
