apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  namespace: vso
  name: vault-connection
spec:
  # address to the Vault server.
  address: https://vault.vault.svc.cluster.local:8200
  skipTLSVerify: true
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: static-auth
  namespace: vso
spec:
  vaultConnectionRef: vault-connection
  # Auth method to use when authenticating to Vault
  method: kubernetes
  # Auth method mount 
  mount: kubernetes
  kubernetes:
    # Vault role to use when authenticating to Vault
    role: test-role
    # ServiceAccount to use when authenticating to Vault
    serviceAccount: default
    audiences:
      - vault
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-kv-app
  namespace: vso
spec:
  type: kv-v2
  # Mount path of kv secrets engine
  mount: test
  # Path of the secret
  path: secret
  # k8s secret location
  destination:
    name: secretkv
    create: true
  # Static secret refresh interval
  refreshAfter: 30s
  # Name of the CRD to authenticate to Vault
  vaultAuthRef: static-auth
