server:
  affinity: ""
  ha:
    enabled: true
    replicas: 6
    raft: 
      enabled: true   
  image:
    repository: hashicorp/vault-enterprise
    tag: 1.12.1-ent
  enterpriseLicense:
    secretName: vault-ent-license
