apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      annotations:
       vault.hashicorp.com/agent-inject: 'true'
       vault.hashicorp.com/role: 'test-app'
       vault.hashicorp.com/agent-inject-secret-password.txt: 'test/data/secret'
      labels:
        app: nginx
    spec:
      serviceAccountName: vault
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
