apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: static-auth
  namespace: vso
spec:
  # Auth method to use when authenticating to Vault
  method: kubernetes
  # Auth method mount 
  mount: kubernetes
  kubernetes:
    # Vault role to use when authenticating to Vault
    role: vso-role
    # ServiceAccount to use when authenticating to Vault
    serviceAccount: default
    audiences:
      - vault