server:
  logLevel: debug
  affinity: ""
  ha:
    enabled: true
    replicas: 3
    raft: 
      enabled: true
      config: | 
        ui = true
        listener "tcp" {
          tls_disable = 1
          address = "[::]:8200"
          cluster_address = "[::]:8201"
        }

        storage "raft" {
            path = "/vault/data"
              retry_join {
                leader_api_addr = "http://vault-0.vault-internal:8200"
            }
            retry_join {
              leader_api_addr = "http://vault-1.vault-internal:8200"
            }
            retry_join {
              leader_api_addr = "http://vault-2.vault-internal:8200"
            }
        }
          
        seal "transit" {
          address = "http://vault-auto-unseal-0.vault-auto-unseal-internal:8200"
          token = "$TOKEN"
          disable_renewal = "false"
          key_name = "autounseal"
          mount_path = "transit/"
          tls_skip_verify = "true"
        }   
  image:
    repository: hashicorp/vault-enterprise
    tag: 1.15.2-ent
  enterpriseLicense:
    secretName: vault-ent-license
injector:
  enabled: false