global:
  enabled: true
  tlsDisable: true
csi:  
  enabled: true
injector:
  enabled: true
  logLevel: debug
server:
  logLevel: debug
  affinity: ""
  auditStorage:
    enabled: true
    mountPath: "/vault/audit"
  ha:
    apiAddr: "http://vault-active.vault.svc.cluster.local:8200"
    clusterAddr: "http://$(HOSTNAME).vault-internal.vault.svc.cluster.local:8201"
    enabled: true
    replicas: 1
  image:
    repository: hashicorp/vault-enterprise
    tag: 1.15.2-ent
  enterpriseLicense:
    secretName: vault-ent-license
  extraEnvironmentVars:
  readinessProbe:
    enabled: false
    path: '/v1/sys/health?standbyok=true&perfstandbyok=true'
  livenessProbe:
    enabled: false
    path: '/v1/sys/health?standbyok=true&perfstandbyok=true'
ui:
  # Use minikube service command to expose service
  enabled: true
  publishNotReadyAddresses: true
  activeVaultPodOnly: false
  serviceType: "LoadBalancer"
  serviceNodePort: null
  externalPort: 8200
  targetPort: 8200

  



  