apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: test-vault-secret
  namespace: vso
spec:
  type: kv-v2
  # mount path
  mount: kvv2
  # path of the secret
  path: test-vault-secret
  # dest k8s secret
  destination:
    name: test-k8s-secret
    create: true
  refreshAfter: 30s
