apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: app-vault-auth
  namespace: default
spec:
  method: kubernetes
  mount: k8s-auth-method
  kubernetes:
    role: vso
    serviceAccount: default



