# vault-values.yaml
server:
  affinity: ""
  ha:
    enabled: true
    replicas: 3
    raft: 
      enabled: true   
  image:
    repository: hashicorp/vault-enterprise
    tag: 1.14.0-ent
  enterpriseLicense:
    secretName: vault-ent-license
  readinessProbe:
    initialDelaySeconds: 10
injector:
  enabled: false
