# Define a SecretProviderClass resource that describes parameters given to the CSI provider
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: test-secretproviderclass
spec:
  provider: vault
  parameters:
    vaultAddress: "http://vault.default:8200"
    roleName: "test-role"
    objects: |
      - objectName: "test-object"
        secretPath: "test/secret"
        secretKey: "password"
